---
- hosts: primary
  name: Setup synchronous replication
  gather_facts: false
  become: true

  collections:
    - edb_devops.edb_postgres

  tasks:

    - name: Update synchronous_standby_names
      community.postgresql.postgresql_query:
        query: >-
          ALTER SYSTEM SET synchronous_standby_names TO 'ANY 1 (postgres3, postgres2)'
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
        db: "{{ pg_database }}"
        autocommit: true
      become: true
      become_user: "{{ pg_owner }}"

    - name: Set synchronous_commit to remote_apply
      community.postgresql.postgresql_query:
        query: >-
          ALTER SYSTEM SET synchronous_commit TO 'remote_apply'
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
        db: "{{ pg_database }}"
        autocommit: true
      become: true
      become_user: "{{ pg_owner }}"

    - name: Reload Postgres configuration
      community.postgresql.postgresql_query:
        query: >-
          SELECT pg_reload_conf()
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
        db: "{{ pg_database }}"
        autocommit: true
      become: true
      become_user: "{{ pg_owner }}"
