---
- hosts: hammerdb
  name: Install HammerDB
  become: true
  gather_facts: true

  tasks:
    - name: Download HammerDB Linux binaries
      ansible.builtin.get_url:
        url: https://github.com/TPC-Council/HammerDB/releases/download/v{{ hammerdb_version }}/HammerDB-{{ hammerdb_version }}-RHEL8.tar.gz
        dest: /tmp/hammerdb.tar.gz
      become: true

    - name: Install HammerDB in {{ hammerdb_install_path }}
      ansible.builtin.command: >
        tar xvzf /tmp/hammerdb.tar.gz -C {{ hammerdb_install_path | dirname }}
      become: true

    - name: Install PostgreSQL client library
      ansible.builtin.package:
        name: postgresql
      become: true
