---
- hosts: all
  name: Populate TPCC database
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Make {{ hammerdb_data_path }} exists
      ansible.builtin.file:
        path: "{{ hammerdb_data_path }}"
        state: directory
      when: "'hammerdb' in group_names"

    - name: Generate HammerDB loader script
      ansible.builtin.template:
        src: loader.tcl.j2
        dest: "{{ hammerdb_data_path }}/loader.tcl"
      when: "'hammerdb' in group_names"

    - name: Wait for Postgres to be ready
      ansible.builtin.command:
        cmd: >
          {{ pg_bin_path }}/pg_isready -d postgres -h {{ pg_unix_socket_directories[0] }}
      become_user: "{{ pg_owner }}"
      register: pg_isready
      until: "pg_isready is not failed"
      retries: 10
      delay: 10
      when: "'primary' in group_names"

    - name: Populate the TPCC database
      ansible.builtin.command:
        cmd: "./hammerdbcli tcl auto {{ hammerdb_data_path }}/loader.tcl"
        chdir: "{{ hammerdb_install_path }}"
      async: 180000
      poll: 60
      changed_when: false
      when: "'hammerdb' in group_names"

    - name: Issuing CHECKPOINT
      community.postgresql.postgresql_query:
        autocommit: true
        query: >-
          CHECKPOINT
        db: "{{ pg_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
      become_user: "{{ pg_owner }}"
      when: "'primary' in group_names"
      async: 180000
      poll: 60

    - name: Create publication
      community.postgresql.postgresql_query:
        autocommit: true
        query: >-
          CREATE PUBLICATION alltables FOR ALL TABLES
        db: "{{ pg_tpcc_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
      become_user: "{{ pg_owner }}"
      when: "'primary' in group_names"


- hosts: standby
  name: Install and initialize Postgres on logical standby nodes
  become: true
  gather_facts: true
  collections:
    - edb_devops.edb_postgres

  roles:
    - role: install_dbserver
    - role: init_dbserver
    - role: tuning

  tasks:
    - name: Apply PostgreSQL tunning
      ansible.builtin.lineinfile:
        path: "{{ pg_data }}/postgresql.auto.conf"
        line: "{{ item.name }} = '{{ item.value }}'"
        create: true
        owner: "{{ pg_owner }}"
        group: "{{ pg_group }}"
      loop: "{{ pg_settings }}"
      become_user: "{{ pg_owner }}"

    - name: Allow TPCC connections on the instance
      ansible.builtin.lineinfile:
        path: "{{ pg_data }}/pg_hba.conf"
        line: "host   all  all  10.0.0.0/24   trust"
      become_user: "{{ pg_owner }}"

    - name: Restart the instance
      ansible.builtin.systemd:
        name: "{{ pg_service }}"
        state: restarted
      become: true

    - name: Export database schema
      ansible.builtin.shell: |
        {{ pg_bin_path }}/pg_dump -h postgres1 -d {{ pg_tpcc_database }} -p {{ pg_port }} -U {{ pg_user }} -s > /tmp/tpcc.sql
      become_user: "{{ pg_owner }}"

    - name: Create database {{ pg_tpcc_database }}
      community.postgresql.postgresql_query:
        autocommit: true
        query: >-
          CREATE DATABASE {{ pg_tpcc_database }}
        db: "{{ pg_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
      become_user: "{{ pg_owner }}"

    - name: Create role tpcc
      community.postgresql.postgresql_query:
        autocommit: true
        query: >-
          CREATE ROLE tpcc
        db: "{{ pg_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
      become_user: "{{ pg_owner }}"

    - name: Restore database schema
      ansible.builtin.command: |
        {{ pg_bin_path }}/psql -p {{ pg_port }} -d {{ pg_tpcc_database }} -f /tmp/tpcc.sql
      become_user: "{{ pg_owner }}"

    - name: Create subscription
      community.postgresql.postgresql_query:
        autocommit: true
        query: |
          CREATE SUBSCRIPTION {{ inventory_hostname }}
          CONNECTION 'host=postgres1 port={{ pg_port }} user={{ pg_user }} dbname={{ pg_tpcc_database }}'
          PUBLICATION alltables
          WITH (binary=true)
        db: "{{ pg_tpcc_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
      become_user: "{{ pg_owner }}"

- hosts: primary
  name: Wait for the end of data synchronisation
  become: true
  gather_facts: false
  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Wait for the end of data synchronisation
      ansible.builtin.command: |
        {{ pg_bin_path }}/psql -tAX -c "SELECT COALESCE(SUM(pg_current_wal_insert_lsn() - confirmed_flush_lsn), 0) AS sum FROM pg_replication_slots" -d {{ pg_tpcc_database }}
      register: sync
      until: sync.stdout == "0"
      retries: 720
      delay: 30
      become_user: "{{ pg_owner }}"
